var={'a':10,'b':20,'c':30}
print(var)
var['d']=40
print(var)
var.update({"e":"50"})
print(var)
print(var.keys())
print(var.values())
print(var.items())
print(var.pop('c'))
print(var)
var['a']=11
print(var)
var['a']=50
print(var)
var['f']=var.pop('a')
print(var)
var['n']=var.pop('d')
print(var)